/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowInfoTimeSeries.java
 *
 * Created on 13-jun-2011, 9:35:27
 */
package guiFinalTest;

import userInterface.*;
import algorithms.Algorithm;
import algorithms.AlgorithmDefaultImplementation;
import algorithms.AlgorithmExecutionInfo;
import algorithms.AlgorithmNotifyPolice;
import algorithms.AlgorithmNotifyPoliceEnum;
import guiTest.SinTimeSeriesGeneratorGui;
import java.lang.Integer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.Set;
import signals.ReadResult;
import signals.SignalManager;
import signals.TimeSeries;

/**
 *
 * @author USUARIO
 */
public class AlgorithmMultiplierOffsetTimeSeriesGui extends javax.swing.JDialog {

    AlgorithmMultiplierOffsetTimeSeries algorithmMultiplierOffsetTimeSeries;

    /** Creates new form ShowInfoTimeSeries */
    public AlgorithmMultiplierOffsetTimeSeriesGui(java.awt.Frame parent, boolean modal, AlgorithmMultiplierOffsetTimeSeries algorithmMultiplierOffsetTimeSeries) {
        super(parent, modal);
        initComponents();
        this.algorithmMultiplierOffsetTimeSeries = algorithmMultiplierOffsetTimeSeries;
        showInfo(algorithmMultiplierOffsetTimeSeries);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSeriesIsGeneratedFrom1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelIdentifier = new javax.swing.JLabel();
        jLabelCurrentIteration = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonAceptarCambios = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldOffset = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMultiplier = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelSignaToWriteIdentifier = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextAreaSeriesIsGeneratedFrom1.setColumns(20);
        jTextAreaSeriesIsGeneratedFrom1.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSeriesIsGeneratedFrom1);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AlgorithmMultiplierOffsetGui");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Identifier:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CurrentIteration:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Offset:");

        jLabelIdentifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIdentifier.setText("Identifier:");

        jLabelCurrentIteration.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelCurrentIteration.setText("Agent:");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonAceptarCambios.setText("Guardar Cambios");
        jButtonAceptarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarCambiosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptarCambios, new java.awt.GridBagConstraints());

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 55, 0, 24);
        jPanel1.add(jButtonSalir, gridBagConstraints);

        jTextFieldOffset.setText("jTextField1");
        jTextFieldOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOffsetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Multiplier:");

        jTextFieldMultiplier.setText("jTextField1");
        jTextFieldMultiplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMultiplierActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("SignalToWriteIdentifier:");

        jLabelSignaToWriteIdentifier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSignaToWriteIdentifier.setText("Agent:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIdentifier))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCurrentIteration))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSignaToWriteIdentifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIdentifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelSignaToWriteIdentifier))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelCurrentIteration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarCambiosActionPerformed
        saveInfo();
        dispose();
}//GEN-LAST:event_jButtonAceptarCambiosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOffsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOffsetActionPerformed

    private void jTextFieldMultiplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMultiplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMultiplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LinkedList<String> eventSignals1;
                LinkedList<String> timeSignals1;
                eventSignals1 = new LinkedList<String>();
                timeSignals1 = new LinkedList<String>();
                timeSignals1.add("TimeSeries1");
                TimeSeries timeSeriesOut1 = new TimeSeries("TimeSeries1_AlgorithmIN", "Algorithm1", 0, 100, "NaN");
                AlgorithmMultiplierOffsetTimeSeries algorithmMultiplierOffsetTimeSeries = new AlgorithmMultiplierOffsetTimeSeries("Algoritm1", timeSeriesOut1, timeSignals1, eventSignals1, new Float(3), new Float(2));

                AlgorithmMultiplierOffsetTimeSeriesGui dialog = new AlgorithmMultiplierOffsetTimeSeriesGui(new javax.swing.JFrame(), true, algorithmMultiplierOffsetTimeSeries);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAceptarCambios;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCurrentIteration;
    private javax.swing.JLabel jLabelIdentifier;
    private javax.swing.JLabel jLabelSignaToWriteIdentifier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaSeriesIsGeneratedFrom1;
    private javax.swing.JTextField jTextFieldMultiplier;
    private javax.swing.JTextField jTextFieldOffset;
    // End of variables declaration//GEN-END:variables

    private void showInfo(AlgorithmMultiplierOffsetTimeSeries algorithmMultiplierOffsetTimeSeries) {
        jLabelIdentifier.setText(algorithmMultiplierOffsetTimeSeries.getIdentifier());
        jLabelSignaToWriteIdentifier.setText(algorithmMultiplierOffsetTimeSeries.getSignalToWrite().getIdentifier());
        jTextFieldOffset.setText(String.valueOf(algorithmMultiplierOffsetTimeSeries.getOffset()));
        jTextFieldMultiplier.setText(String.valueOf(algorithmMultiplierOffsetTimeSeries.getMultiplier()));
    }

    private void saveInfo() {
        this.algorithmMultiplierOffsetTimeSeries.setMultiplier(Float.valueOf(jTextFieldMultiplier.getText()));
        this.algorithmMultiplierOffsetTimeSeries.setOffset(Float.valueOf(jTextFieldOffset.getText()));
    }
}
