/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowInfoTimeSeries.java
 *
 * Created on 13-jun-2011, 9:35:27
 */
package userInterface;

import java.util.ArrayList;
import signals.EventSeries;
import signals.TimeSeries;

/**
 *
 * @author USUARIO
 */
public class ShowInfoEventSeries extends javax.swing.JDialog {

    /** Creates new form ShowInfoTimeSeries */
    public ShowInfoEventSeries(java.awt.Frame parent, boolean modal, EventSeries eventSeries) {
        super(parent, modal);
        initComponents();
        showInforSignalName(eventSeries);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelIdentifier = new javax.swing.JLabel();
        jLabelAgent = new javax.swing.JLabel();
        jLabelUnits = new javax.swing.JLabel();
        jLabelOrigin = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSeriesIsGeneratedFrom = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EventSeries");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Identifier:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Agent:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Units:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Origin:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("SeriesIsGeneratedFrom:");

        jLabelIdentifier.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabelIdentifier.setText("Identifier:");

        jLabelAgent.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelAgent.setText("Agent:");

        jLabelUnits.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelUnits.setText("Units:");

        jLabelOrigin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelOrigin.setText("Origin:");

        jTextAreaSeriesIsGeneratedFrom.setColumns(20);
        jTextAreaSeriesIsGeneratedFrom.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSeriesIsGeneratedFrom);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIdentifier))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAgent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUnits))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOrigin))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIdentifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelOrigin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                ArrayList<String> seriesIsGeneratedFrom=new ArrayList<String>();
                seriesIsGeneratedFrom.add("EventSeries1");
                seriesIsGeneratedFrom.add("EventSeries2");
                seriesIsGeneratedFrom.add("TimeSeries1");
                EventSeries eventSeries=new EventSeries("Señal1", "Simulated", 0, seriesIsGeneratedFrom, "mW");

                ShowInfoEventSeries dialog = new ShowInfoEventSeries(new javax.swing.JFrame(), true, eventSeries );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAgent;
    private javax.swing.JLabel jLabelIdentifier;
    private javax.swing.JLabel jLabelOrigin;
    private javax.swing.JLabel jLabelUnits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaSeriesIsGeneratedFrom;
    // End of variables declaration//GEN-END:variables

    private void showInforSignalName(EventSeries eventSeries) {
        jLabelIdentifier.setText(eventSeries.getIdentifier());
        jLabelAgent.setText(eventSeries.getAgent());
        jLabelUnits.setText(eventSeries.getUnits());
        jLabelOrigin.setText(Long.toString(eventSeries.getOrigin()));
        ArrayList<String> seriesIsGeneratedFrom = eventSeries.getSeriesIsGeneratedFrom();
        String stringIsGeneratedFrom = "";
        for (String serie : seriesIsGeneratedFrom) {
            stringIsGeneratedFrom=stringIsGeneratedFrom.concat(serie+"\n");
        }
        stringIsGeneratedFrom=stringIsGeneratedFrom.concat("\n");
        jTextAreaSeriesIsGeneratedFrom.setText(stringIsGeneratedFrom);

        
    }
}
